{"name": "test_login01[case1]", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'url'", "trace": "self = <testcase.test_login.TestLogin object at 0x000002D730CE7EE0>\ncase = {'case_data': \"{'username':'admin1','password':'admin'}\", 'case_id': 2, 'case_title': '输入错误的用户名', 'res': \"{'msg':'失败','code':'9999'}\", ...}\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        # allure.dynamic.title(case.case_title)\n>       allure.attach(body=case.url, name='接口路径')\nE       AttributeError: 'dict' object has no attribute 'url'\n\ntestcase\\test_login.py:20: AttributeError"}, "parameters": [{"name": "case", "value": "{'case_id': 2, 'case_title': '输入错误的用户名', 'url': 'www.baidu.com', 'case_data': \"{'username':'admin1','password':'admin'}\", 'res': \"{'msg':'失败','code':'9999'}\"}"}], "start": 1650275445288, "stop": 1650275445288, "uuid": "e8db0ee4-bba7-4dbc-9090-d7cc4682aad0", "historyId": "e61a131eafdd190c3a5f0c00ce5a5d87", "testCaseId": "f0a3740a932ee8262933e5b94534ef30", "fullName": "testcase.test_login.TestLogin#test_login01", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "小扁豆"}, {"name": "thread", "value": "6012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}