{
  "uid" : "82a0b0a73f9345c7",
  "name" : "test_login01[case2]",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "f1448aed770d7fdd91df4365d7b3461a",
  "time" : {
    "start" : 1650292603209,
    "stop" : 1650292603216,
    "duration" : 7
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'act_res' is not defined",
  "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600C8CD0>\ncase = <comon.excel_util.CaseData object at 0x000002566007B610>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "NameError: name 'act_res' is not defined",
    "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600C8CD0>\ncase = <comon.excel_util.CaseData object at 0x000002566007B610>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "90b356dd1f70810",
      "name" : "接口路径",
      "source" : "90b356dd1f70810.attach",
      "type" : "text/plain",
      "size" : 42
    }, {
      "uid" : "3ffa3d4d5abe0918",
      "name" : "请求参数",
      "source" : "3ffa3d4d5abe0918.attach",
      "type" : "text/plain",
      "size" : 167
    }, {
      "uid" : "664130616f23526b",
      "name" : "预期结果",
      "source" : "664130616f23526b.attach",
      "type" : "text/plain",
      "size" : 62
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Mikey"
  }, {
    "name" : "thread",
    "value" : "15044-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x000002566007B610>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "82a0b0a73f9345c7.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x000002566007B610>" ]
}